project:
  type: website

format:
  html:
    theme: cosmo

# Python environment (path to python binary, not activate script)
python: pyenv/bin/python

# Enable renv integration for R
r:
  renv: true
